export const REGIONS_DISTRICTS: Record<string, string[]> = {
    "Eastern": ["Kailahun", "Kenema", "Kono"],
    "Northern": ["Bombali", "Falaba", "Koinadugu", "Tonkolili"],
    "North West": ["Kambia", "Karene", "Port Loko"],
    "Southern": ["Bo", "Bonthe", "Moyamba", "Pujehun"],
    "Western Area": ["Western Area Rural", "Western Area Urban"],
};

export const MDAS = [
    "Ministry of Agriculture and Food Security",
    "Ministry of Basic and Senior Secondary Education",
    "Ministry of Defence",
    "Ministry of Energy",
    "Ministry of Environment and Climate Change",
    "Ministry of Finance",
    "Ministry of Fisheries and Marine Resources",
    "Ministry of Foreign Affairs",
    "Ministry of Gender and Children's Affairs",
    "Ministry of Health and Sanitation",
    "Ministry of Information and Civic Education",
    "Ministry of Internal Affairs",
    "Ministry of Justice",
    "Ministry of Labour and Social Security",
    "Ministry of Lands, Housing and Country Planning",
    "Ministry of Local Government and Community Affairs",
    "Ministry of Mines and Mineral Resources",
    "Ministry of Planning and Economic Development",
    "Ministry of Public Administration and Political Affairs",
    "Ministry of Social Welfare",
    "Ministry of Technical and Higher Education",
    "Ministry of Tourism and Cultural Affairs",
    "Ministry of Trade and Industry",
    "Ministry of Transport and Aviation",
    "Ministry of Water Resources",
    "Ministry of Works and Public Assets",
    "Ministry of Youth Affairs",
    "National Revenue Authority (NRA)",
    "Sierra Leone Police (SLP)",
    "Electricity Distribution and Supply Authority (EDSA)",
    "Sierra Leone Roads Authority (SLRA)",
    "National Commission for Social Action (NaCSA)",
];